# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'IdeaCatcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IdeaCatcher

  target 'IdeaCatcherTests' do
    inherit! :search_paths
    # Pods for testing
pod 'HubFramework'
  end

end
